version: '2'

services: 
    front-end:
       image: registry.gitlab.com/vmwarecloudadvocacy/front-end:latest
       hostname: front
       restart: always
       ports:
          - '3000:3000'
       cap_drop:
           - all
       cap_add:
           - NET_BIND_SERVICE
       read_only: true
    users:
       image: registry.gitlab.com/vmwarecloudadvocacy/user:latest
       hostname: users
       restart: always
       cap_drop:
           - all
       cap_add:
           - NET_BIND_SERVICE
       environment:
           - USERS_DB_USER=mongoadmin
           - USERS_DB_SECRET=secret
           - USERS_DB_IP=192.168.152.218
           - USERS_PORT=80
    catalog:
        image: registry.gitlab.com/vmwarecloudadvocacy/catalog:latest
        hostname: catalog
        restart: always
        cap_drop:
          - all
        cap_add:
          - NET_BIND_SERVICE
        environment:
             - CATALOG_DB_USER=mongoadmin
             - CATALOG_DB_SECRET=secret
             - CATALOG_DB_IP=192.168.152.218
             - CATALOG_PORT=80
      


          
