apiVersion: v1
kind: Service
metadata:
  name: cart
  labels:
    app: acmefit
spec:
  ports:
    - name: cart
      protocol: TCP
      port: 5000
      nodePort: 30431
  selector:
    app: acmefit
  type: NodePort
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: cart
  labels:
    app: acmefit
spec:
  selector:
    matchLabels:
      app: acmefit
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: acmefit
    spec:
      volumes:
      - name: acmefit-cart-data
        emptyDir: {}
      containers:
      - image: gcr.io/vmwarecloudadvocacy/acmeshop-cart
        name: cart
        env:
        - name: REDIS_HOST
          value: 'cart-redis'
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: redis-pass
              key: password
        - name: REDIS_PORT
          value: '6379'
        - name: CART_PORT
          value: '5000'
        ports:
        - containerPort: 5000
          name: cart
        volumeMounts:
        - mountPath: "/data"
          name: "acmefit-cart-data"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
