apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: catalog-db
  name: catalog-db
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: catalog-db
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_DATABASE
          value: acmefit
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: secret
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongoadmin
        image: gcr.io/vmwarecloudadvocacy/acmeshop-catalog-db:latest
        name: catalog-db
        resources: {}
        securityContext:
          capabilities:
            add:
            - CHOWN
            - SETGID
            - SETUID
      hostname: catalog-db
      restartPolicy: Always
status: {}
