apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: front-end
  name: front-end
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: front-end
    spec:
      containers:
      - env:
        - name: CART_HOST
          value: cart
        - name: CART_PORT
          value: "5000"
        - name: CATALOG_HOST
          value: catalog
        - name: CATALOG_PORT
          value: "8082"
        - name: ORDER_HOST
          value: order
        - name: ORDER_PORT
          value: "6000"
        - name: PORT
          value: "3000"
        - name: USERS_HOST
          value: user
        - name: USERS_PORT
          value: "8081"
        image: gcr.io/vmwarecloudadvocacy/acmeshop-front-end:latest
        name: front-end
        ports:
        - containerPort: 3000
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
      hostname: front-end
      restartPolicy: Always
status: {}
