apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: fitcycle
    service: order
spec:
  ports:
    - name: order
      protocol: TCP
      port: 5000
      nodePort: 30433
  selector:
    app: fitcycle
    service: order
  type: NodePort
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: order
  labels:
    app: fitcycle
    service: order
spec:
  selector:
    matchLabels:
      app: fitcycle
      service: order
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: fitcycle
        service: order
    spec:
      volumes:
      - name: fitcycle-order-data
        emptyDir: {}
      containers:
      - image: gcr.io/vmwarecloudadvocacy/acmeshop-order:latest
        name: order
        env:
        - name: ORDER_DB_HOST
          value: 'order-mongo'
        - name: ORDER_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: order-mongo-pass
              key: password
        - name: ORDER_DB_PORT
          value: '27017'
        - name: ORDER_DB_USERNAME
          value: 'mongoadmin'
        - name: ORDER_PORT
          value: '5000'
        ports:
        - containerPort: 5000
          name: order
        volumeMounts:
        - mountPath: "/data"
          name: "fitcycle-order-data"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
