apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: fitshop
spec:
  ports:
    - name: payment
      protocol: TCP
      port: 9000
      nodePort: 30440
  selector:
    app: fitshop
  type: NodePort
---
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: payment
  labels:
    app: fitshop
spec:
  selector:
    matchLabels:
      app: fitshop
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: fitshop
    spec:
      containers:
      - image: gcr.io/vmwarecloudadvocacy/acmeshop-payment
        name: payment
        env:
        - name: PAYMENT_PORT
          value: '9000'
        ports:
        - containerPort: 9000
          name: payment
