apiVersion: v1
kind: Service
metadata:
  name: users
  labels:
    app: fitcycle
    service: users
spec:
  ports:
    - name: users
      protocol: TCP
      port: 8082
      nodePort: 30435
  selector:
    app: fitcycle
    service: users
  type: NodePort
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: users
  labels:
    app: fitcycle
    service: users
spec:
  selector:
    matchLabels:
      app: fitcycle
      service: users
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: fitcycle
        service: users
    spec:
      volumes:
      - name: fitcycle-users-data
        emptyDir: {}
      containers:
      - image: gcr.io/vmwarecloudadvocacy/acmeshop-user:latest
        name: users
        env:
        - name: USERS_DB_HOST
          value: 'users-mongo'
        - name: USERS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: users-mongo-pass
              key: password
        - name: USERS_DB_PORT
          value: '27017'
        - name: USERS_DB_USERNAME
          value: 'mongoadmin'
        - name: USERS_PORT
          value: '8082'
        ports:
        - containerPort: 8082
          name: users
        volumeMounts:
        - mountPath: "/data"
          name: "fitcycle-users-data"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
