version: '3'

services: 
    mongo-db:
      image: gcr.io/vmwarecloudadvocacy/acmefitness-mongo-db
      hostname: mongo-db
      ports:
        - '27017:27017'
      environment:
        - MONGO_INITDB_ROOT_USERNAME=mongoadmin 
        - MONGO_INITDB_ROOT_PASSWORD=secret
        - MONGO_INITDB_DATABASE=acmefit
      cap_add:
        - CHOWN
        - SETGID
        - SETUID
      tmpfs:
        - /tmp:rw,noexec,nosuid
    front-end:
       image: gcr.io/vmwarecloudadvocacy/acmefitness-front-end
       hostname: front-end
       restart: always
       ports:
          - '3000:3000'
       cap_add:
           - NET_BIND_SERVICE
       environment:
           - USERS_HOST=users
           - CATALOG_HOST=catalog
           - CART_HOST=cart   
           - USERS_PORT=8081
           - CATALOG_PORT=8082
           - CART_PORT=5000
    users:
       image: gcr.io/vmwarecloudadvocacy/acmefitness-users
       hostname: users
       restart: always
       cap_add:
           - NET_BIND_SERVICE
       environment:
           - USERS_DB_USERNAME=mongoadmin
           - USERS_DB_PASSWORD=secret
           - USERS_DB_HOST=mongo-db
           - USERS_DB_PORT=27017
           - USERS_PORT=8081
       depends_on:
           - mongo-db    
    catalog:
        image: gcr.io/vmwarecloudadvocacy/acmefitness-catalog
        hostname: catalog
        restart: always
        cap_add:
          - NET_BIND_SERVICE
        environment:
             - CATALOG_DB_USERNAME=mongoadmin
             - CATALOG_DB_PASSWORD=secret
             - CATALOG_DB_HOST=mongo-db
             - CATALOG_PORT=8082
             - CATALOG_DB_PORT=27017
        depends_on:
             - mongo-db
    redis-db:
      image: redis:5.0.3-alpine
      hostname: redis-db
      restart: always
      ports:
        - '6379:6379'
    cart:
      image: gcr.io/vmwarecloudadvocacy/acmefitness-cart
      hostname: cart
      restart: always
      environment:
          - REDIS_HOST=redis-db
          - REDIS_PORT=6379
          - CART_PORT=5000
      ports:
          - '5000:5000'
      depends_on:
          - redis-db
    order:
      image: gcr.io/vmwarecloudadvocacy/acmefitness-order
      hostname: order
      restart: always
      environment:
          - PAYMENT_HOST=payment
          - ORDER_PORT=6000
          - ORDER_DB_HOST=mongo-db
          - ORDER_DB_PASSWORD=secret
          - ORDER_DB_USERNAME=mongoadmin
      depends_on:
          - payment
          - mongo-db
    payment:
      image: gcr.io/vmwarecloudadvocacy/acmefitness-payment
      hostname: payment
      restart: always 

      
      


          
